### ISSUE TITLE
Catalina

### ISSUE THREAD

**Issue by jhabdas** [Dunedan/mbp-2016-linux#121]
I'm working on an Arch dual-boot on a DMCtypt partition with Catalina once the download finishes. Assuming T2 disabled etc. I'm interested to hear now that Catalina "runs in its own dedicated system volume" ([as reported](https://www.youtube.com/watch?v=qxdkIcjn260) by 9to5 Mac, 9:20) how we can make Linux on MBP a thing. I'll be attempting this on a 2019.

**Comment by ClashTheBunny** [comment]
Apfs volumes are different from partitions.  It's more like btrfs and zfs than a classic FS.

**Comment by jhabdas** [comment]
That's fine, I just threw on an ExFat temporarily so I can try booting from USB-C, hopefully it goes off without a hitch like it did on the LUKS partition I used DMCrypt to create on my MacBomb https://habd.as/post/dual-boot-manjaro-mojave-macbook-pro/

**Comment by Helios747** [comment]
This repo appears to be about the 2016/7 macbooks, so I'm not sure how relevant running Linux on a 2019 model is here.

If it's anything like the current state of 2016/7 models though, probably pretty miserable. The issue isn't getting it installed and booting.

**Comment by jhabdas** [comment]
Found a workaround because I needed Arch. Will post here shortly and will close this issue with my solution.

**Comment by julian-alarcon** [comment]
What was your solution @jhabdas ?

**Comment by jhabdas** [comment]
Docker inside Hyper. CLI sneak preview info here: https://t.me/afterdarkhugo/13928

**Comment by jhabdas** [comment]
@julian-alarcon wip solution https://git.habd.as/comfusion/archuro/src/branch/master/bin/archuro
