### ISSUE TITLE
iMac19,1 has very low successful boot rate 

### ISSUE THREAD

**Issue by CuriousTommy** [Dunedan/mbp-2016-linux#122]
My Parent's 2019 iMac has a very high failure rate when I try to boot Fedora 30 from my portable drive. It often gets stucks on the loading screen, after I enter my encryption password.

I tried to update the boot arguments to remove quiet mode, but it doesn't seem to provide any useful information (I have to press ESC to get any useful information). 

Here is a screenshot of the issue. It seems to always fail after setting up the backlight.
![IMG_20190920_214450](https://user-images.githubusercontent.com/3105794/66703895-2b924300-eccc-11e9-96d3-b2d95ffe7a71.jpg)

**Comment by CuriousTommy** [comment]
On rare occasions, the iMac may freeze after boot (fans tend to spin up), but that normally doesn't happen.

**Comment by Dunedan** [comment]
Do you have any updates on this issue?

**Comment by CuriousTommy** [comment]
From recent testing, it seems to boot fine now (or at least the boot error rate is very low). I'll close this issue.
