### ISSUE TITLE
applespi module not compiled into stock Fedora kernel 5.3+

### ISSUE THREAD

**Issue by monkcs** [Dunedan/mbp-2016-linux#124]
Hello!
Maybe this is the wrong place to ask, and if so I apologize in advance!

I have upgraded my kernel to 5.3.7, to be able to use my MacbookPro14,1 on Fedora 30/31 without to have to manually install the applespi module from [roadrunner2](https://github.com/roadrunner2/macbook12-spi-driver). But the in-tree module is not available to modprobe or list as a driver compiled into the kernel.

After some digging, I found (as I understand) that the module is not compiled with the kernel because it is not set in the `/lib/modules/5.3.7-301.fc31.x86_64/config` file.

A `grep APPLE` on the file returns this:

CONFIG_APPLE_PROPERTIES=y
CONFIG_DEV_APPLETALK=m
**\# CONFIG_KEYBOARD_APPLESPI is not set**
CONFIG_MOUSE_APPLETOUCH=m
CONFIG_SENSORS_APPLESMC=m
CONFIG_BACKLIGHT_APPLE=m
CONFIG_HID_APPLE=m
CONFIG_HID_APPLEIR=m
CONFIG_USB_APPLEDISPLAY=m
CONFIG_APPLE_GMUX=m

To the question: Does anyone know if there is a way to include applespi to get compiled?
If so, is it possible to make this automatic (so I don't need to recompile by myself every new kernel?).

Or is there another way, like downloading a rpm or something?
Should one file a bug to Fedora about not leaving out the module?

I have been trying to search around for some answer, but have not found anything yet.
Please tell if I'm completely in the wrong direction!

Thanks in advance, :smile:

**Comment by christophgysin** [comment]
> Should one file a bug to Fedora about not leaving out the module?

This is the right approach to get it fixed for all fedora users from the next kernel release onwards.

Until then, you can always build the module yourself. Source and instructions can be found at:
https://github.com/cb22/macbook12-spi-driver

**Comment by Dunedan** [comment]
I recently opened a bug for Debian to get the `applespi`-driver included there as well: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=943337
So far no response.

**Comment by leifliddy** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1769465

**Comment by leifliddy** [comment]
applespi support has been added to Fedora kernel
```
# grep CONFIG_KEYBOARD_APPLESPI  /boot/config-5.3.11-300.fc31.x86_64 
CONFIG_KEYBOARD_APPLESPI=m
```

**Comment by marc-git** [comment]
> I recently opened a bug for Debian to get the `applespi`-driver included there as well: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=943337
> So far no response.

looks like this has been reallocated to source in a long list of unclassified normal severity bugs.

**Comment by monkcs** [comment]
Tested on Fedora 31, keyboard working out of the box
