### ISSUE TITLE
Discussion of support for MacBookPro16,1?

### ISSUE THREAD

**Issue by niem94** [Dunedan/mbp-2016-linux#132]
Hi I wanted to post this, to have a place to keep track of macbookpro16,1 support. I've tried Ubuntu 19.10 and It does boot, but the SSD is not recognised.

**Comment by Dunedan** [comment]
As the general discussion thread for the MacBookPro15,1 and 15,2 turned into a total mess with hundreds of comments which make it very difficult to find information in there, please open component specific issues (e.g. one for the SSD-supporti n the MacBookPro16,1), so it's possible to have more focused discussions. For general discussion there is a Gitter chat available: https://gitter.im/mbp-2016-linux/Lobby
