### ISSUE TITLE
MacBook Air 2020

### ISSUE THREAD

**Issue by solna86** [Dunedan/mbp-2016-linux#141]
Thanks for a great project. I was considering to buy a MacBook Air 2020 to run Linux, which will be in stock here in a few weeks time and help getting it supported under Linux.

Shall I expect to encounter the same audio roadblock present in other models? You have some dumps from MacBookAir8,1 but no reports on what works / what is missing. Somewhere, you state it has the same internal architecture as the touchbar MacBook Pro. Does this refer to the T2 chip only, or also other components.

**Comment by Dunedan** [comment]
Help in getting new hardware supported is highly appreciated. :+1:

You should expect the same if not more hardware incompatibilities for now as for the existing models. While it's probably similar to the existing models, nobody knows yet if and what Apple changed for this new model.

To avoid such messy Github issues as #71 with hundreds of comments, I'm going to close this issue now. However please be encouraged to open issues per component which require work, once you got your MacBook Air 2020.
