### ISSUE TITLE
Audio works with workaround on MacBookPro14,3

### ISSUE THREAD

**Issue by vxcamiloxv** [Dunedan/mbp-2016-linux#152]
Audio works in speakers (with a little noise after in a high volume  level), headphones (perfect), microphone not work on Debian with kernel ´5.6.0-2-amd64´ and this patch https://github.com/davidjo/snd_hda_macbookpro on MacBookPro14,3 (2018)

**Comment by treymerkley** [comment]
Try restarting pulse, that's worked for me for getting crackling fixed on Manjaro with KDE5

**Comment by MrAsimov** [comment]
@treymerkley @vxcamiloxv  can you guys provide me the hwinfo and dmesg and arecord information of MBP14,3 model so I can update the pull request over at https://github.com/Dunedan/mbp-2016-linux/pull/149 ?

Thanks

**Comment by vxcamiloxv** [comment]
mine [dmesg](https://termbin.com/jvazl) and [hwinfo](https://termbin.com/nlb2)

**Comment by MrAsimov** [comment]
@vxcamiloxv  Thank you, it has already been added over at the pull request https://github.com/Dunedan/mbp-2016-linux/pull/149

**Comment by andyholst** [comment]
@vxcamiloxv you should close this issue since the documentation of the README.md has been updated for the audio section.

**Comment by Dunedan** [comment]
@vxcamiloxv Did you manage to get the microphone to work in the meanwhile? If not, we should probably adjust the README, as it currently states that audio input works for the MacBookPro14,3.

**Comment by vxcamiloxv** [comment]
let me check the mic again

**Comment by andyholst** [comment]
@vxcamiloxv it has been verified that the mic is working for MBP model 14,4 at https://github.com/davidjo/snd_hda_macbookpro/issues/12 for kernel version 5.5+.

**Comment by vxcamiloxv** [comment]
I confirm that the audio/internal mic are working fine with debian 10 - linux kernel 5.9 but with headphones only work audio

**Comment by andyholst** [comment]
@vxcamiloxv Right,the audio input/output works just fine for MBP 14,3. You should again close this issue.
