### ISSUE TITLE
Some Problems with Macbook Pro 16,2 (Wifi,BT,Touchbar and shim-signed)

### ISSUE THREAD

**Issue by kami83** [Dunedan/mbp-2016-linux#154]
Hi, 

i am using a MBP 2020 with Linux. 

-The Wifi is not working as mentioned here before. Still looking for a firmware. Has anyone tested the Mojave Firmware?
- Bluetooth is also not working. Has anyone tested this?
- My Touchbar is working with the apple-ib-tb modules, but the 10 keys have strange functions? Where can i configure this?
- I am trying to enabled Secure Boot (for now only refind without SIP and Secure Boot is working really fine). If i try to use any signed version of shim or Preloader my system is not booting and it is always starting in recovery mode. If i try the Windows or Mac OS Bootloader with Medium Security, everything is fine. Can someone tell me how to debug this? If i only use the shimx64.efi with no bootloader like grubx64.efi there is no output just the recovery mode. Is this right or should there be any other output?

Thanks a lot.

Cu kami

**Comment by Dunedan** [comment]
To keep the Github issues clear and focused, please open one issue per topic. For questions regarding the TouchBar driver https://github.com/roadrunner2/macbook12-spi-driver might be a better place to get support.

I'm closing this issue now, but feel free to open issues for component specific issues.
