### ISSUE TITLE
Would this driver work on an iMac retina mid-2017

### ISSUE THREAD

**Issue by EimaKve** [Dunedan/mbp-2016-linux#182]
Last time when I installed linux on it it couldn't output any audio and had to reinstall MacOS. Now I am wondering if this would work on an iMac, but I don't wanna waste time again if there's already an answer for it

**Comment by sn3rd** [comment]
Audio worked out-of-the-box for me with an iMac Retina Late 2015 (iMac17,1) on an Ubuntu 22.04 live disk.

**Comment by EimaKve** [comment]
Closing this issue since I got audio working by using this [repo](https://github.com/davidjo/snd_hda_macbookpro) and following the instructions from [here](https://github.com/davidjo/snd_hda_macbookpro/issues/59)
