### ISSUE TITLE
Crashes to blank colored screen, then reboots after 30s [solved]

### ISSUE THREAD

**Issue by vjpr** [Dunedan/mbp-2016-linux#185]
# Solved

Solution here: https://github.com/Dunedan/mbp-2016-linux/issues/185#issuecomment-1188337689

# Issue

Happens after 30s or so or when I do an action like clicking on settings or something.

Testing with Ubuntu 22.04.

```
$ uname -r

5.15.0-41-generic
```

# Devices detected

```
$ lspci -nnk | grep 'VGA'

...only lists the amd driver, not the intel
```

There is no Intel one. This is discussed here: https://github.com/Dunedan/mbp-2016-linux/issues/6

# Tried

## Latest gpu drivers

Installed latest amd drivers: https://www.amd.com/en/support/graphics/amd-radeon-5500-series/amd-radeon-rx-5500-series/amd-radeon-rx-5500-xt

Used Ubuntu recovery mode with ethernet networking.

Checking version...

From recovery mode:

```
$ apt show amdgpu
22.20.50200-1438747~22.04
```

After booting to GUI:

```
$ sudo lshw -c video

...
driver=amdgpu
...
```

# Crash logs

Used this command to examine the crash logs.

NOTE: You must choose the correct setting for `-b <boot number>`. Usually `-1` will work. It should be quite noisy compared to the recovery mode log which ends with `journalctl flushing` if you shut it down with `reboot now`.

```
$ journalctl --list-boots
$ journalctl -b -1 -e -t kernel
```

Saw some libinput errors about trackpad. Will try with external mouse.

---

Related: https://askubuntu.com/questions/1214678/dual-booted-2016-macbook-pro-suddenly-shows-seemingly-random-color-for-30-second

**Comment by vjpr** [comment]
# Update

When I boot into recovery mode, and then select "resume boot", it says some warning that "sometimes gpu drivers miay require a full reboot". However, when the OS loads, it does not crash anymore!

So it's probably the GPU drivers. However, the keyboard, trackpad drivers don't load either in this mode. So it could also be them.

It seems the `amdgpu` driver is causing it because in this boot from recovery mode, this driver doesn't load.

```
$ sudo lshw -c video

*-display
 ...
 configuration: latency=0
 ...

*-graphics
  product: EFI VGA
```

**Comment by vjpr** [comment]
# Solution

Use https://github.com/0xbb/gpu-switch.

## Install rEFInd + apple_set_os.efi

From the Recovery Mode, follow Ubuntu instructions here: http://www.rodsbooks.com/refind/installing.html#packagefile.

NOTE: Refind's `spoof_osx_version` is not working after later macOS has been installed. So you need to use the https://github.com/0xbb/apple_set_os.efi approach. Just follow instructions.

## Install gpu-switch

It's just a shell script. Just `wget` it's raw contents.

https://github.com/0xbb/gpu-switch

`./gpu-switch -i`

## Update X config

See: https://github.com/Dunedan/mbp-2016-linux/issues/6#issuecomment-286168538

```
$ cat /etc/X11/xorg.conf.d/20-intel.conf 
Section "Device"
	Identifier "Intel Graphics"
	Driver "intel"
	BusID "PCI:0:2:0"
	Option "TearFree" "true"
	Option "AccelMethod" "glamor"
EndSection
```

## Blacklist amdgpu and radeon

See: https://askubuntu.com/questions/1080217/how-to-blacklist-amdgpu-driver

## Other guides

This is a good guide (except we use refind instead of grub)

https://github.com/Dunedan/mbp-2016-linux/issues/6#issuecomment-387526390

**Comment by vjpr** [comment]
# Wayland issues

Everything is working with iGPU. But to get the `barrier` tool working I had to disable wayland and use X11. When running `sudo modprobe amdgpu` I found that I could use the AMD driver and it wouldn't crash anymore.

So looks like Wayland was crashing `amdgpu` - which the symptoms seemed to indicate.

## Built in monitor

When I unblacklisted the `amdgpu` it works. It loads a screen with a blinking `_` in the top-left corner, but then it loads. I still have the X11 mods in place.

## External monitor

When I unblacklisted the `amdgpu` and had my external monitor plugged in I got this:

```
[amdgpu] atombios stuck in loop for more than 20secs aborting
```

If I didn't run the osx_spoof thingy, then it would be blinking this message.

# Nope

It didn't work. Still crashes when using `amdgpu` for X11 or Wayland.

So when `amdgpu` is used for the window manager, that is crashing the GPU.

`amdgpu` xorg config is here:

_/usr/share/X11/xorg.conf.d/00-amdgpu.conf_

```
Section "OutputClass"
	Identifier "AMDgpu"
	MatchDriver "amdgpu"
	Driver "amdgpu"
EndSection

Section "Files"
	ModulePath "/opt/amdgpu-pro/lib/xorg/modules"
	ModulePath "/opt/amdgpu/lib/xorg/modules"
	ModulePath "/usr/lib/xorg/modules"
EndSection
```

```
ls /opt/amdgpu/lib/xorg/modules/drivers

amdgpu_drv.so
```

# Ideas

Could be an issue with the xorg amdgpu driver

https://man.archlinux.org/man/amdgpu.4
https://gitlab.freedesktop.org/xorg/driver/xf86-video-amdgpu

**Comment by vjpr** [comment]
# Just works now

After one last try, I removed the xorg intel config, used gpu-switch to enable discrete, and didn't run the osx_spoof thing, and it loaded with external monitor working, and it doesn't seem to crash.

I immediately tailed the logs of xorg. Everything seems normal.

So strange. Maybe it is a hardware issue.

At least I can now collect some logs from a fresh startup.

**Comment by pvraj** [comment]
Hello @vjpr ,
I know this was a few years ago, but were you ever able to successfully run with the AMD GPU with kernel versions 6.X? Or did you have to stay on kernel 5.X to fix these graphics issues?

 I've tried setting up ubuntu twice, and the only thing keeping it from being useable is these graphics crashes seemingly caused by the AMD GPU (460 Pro in my case, 15 inch 2016 model). Adding the `nomodeset` flag helps but then it uses llvmpipe for rendering which significantly degrades perfomrance; I would prefer to get the AMD GPU working (though if I can force only the intel GPU, that would be great also). I found some other threads mentioning graphics issues https://github.com/Dunedan/mbp-2016-linux/issues/142, but they are all many years older and around kernel version 5. 

I'm on Ubuntu 22.04 and tried both with kernel versions `6.8.0-40-generic` and `6.8.0-138-generic`, and both crash unless I use `nomodeset`. No obvious error logs spotted in `dmesg`.  Thanks!
