### ISSUE TITLE
Can screen brightness be modified?

### ISSUE THREAD

**Issue by berglh** [Dunedan/mbp-2016-linux#2]
This patch fixed the gmux control of brightness on the MBP 11,5. Maybe this patch is already upstream now? This was a problem on Ubuntu Gnome 16.04/16.10: https://bugzilla.kernel.org/show_bug.cgi?id=105051

**Comment by Dunedan** [comment]
I don't have a MacBook Pro with AMD graphics, so I can't test if that's still an issue. If you or somebody else can, I'd be happy to include it into the notes.

**Comment by roadrunner2** [comment]
Thanks @berglh! That patch indeed fixed the issue on MacBookPro13,3. I've updated my instructions accordingly.

**Comment by Dunedan** [comment]
Thanks @berglh. I updated my instructions as well.
Would be still quite good if somebody could put effort into getting that patch upstream. Volunteers?

**Comment by Dunedan** [comment]
Closing this as it's properly documented in the README.
