### ISSUE TITLE
Screen flickering on latest kernel?

### ISSUE THREAD

**Issue by berglh** [Dunedan/mbp-2016-linux#3]
This was an issue on Gnome Shell and any recent kernels.
https://bugs.freedesktop.org/show_bug.cgi?id=98897#c22

**Comment by roadrunner2** [comment]
Looks like an issue when using the radeon driver only - I see no problems using the amdgpu driver (default).

**Comment by berglh** [comment]
Yes, that would be true. Good to hear it's supported by the amdgpu driver,
I didn't think about that. (I don't actually have one of these.. yet). Just
thought I'd look to see what the support was like. This can be closed as
irrelevant of course.
