### ISSUE TITLE
USB hotplugging

### ISSUE THREAD

**Issue by peterychuang** [Dunedan/mbp-2016-linux#36]
Hi, I'm wondering if anyone finds hotplugging USB devices (e.g. flash drive) kind of hit-or-miss.

**Comment by Dunedan** [comment]
I had no problems at all with USB so far, but I remember somebody having problems with certain flash drives/USB-C adapters.

**Comment by roadrunner2** [comment]
I haven't run into any issues either, but then again I've only tried a handful of devices (a CD/DVD player, a thumbdrive, and external ssd, and two wifi sticks) - all of them via Apple USB-C adapter.

**Comment by risen** [comment]
I had issues, but it turned out to be my el-cheapo USB-C to USB type-A adapter that was broken. Eventually it stopped working completely.

**Comment by peterychuang** [comment]
Thanks everyone.
I have most problems with this [Sandisk flash drive (32GB)](https://www.amazon.com/SanDisk-Ultra-Drive-Type-C-SDDDC2-032G-G46/dp/B01EZ0X23W). It could be indeed the problem with the flash drives. Will investigate further.

**Comment by Dunedan** [comment]
Is this still an issue or can we close it?

**Comment by peterychuang** [comment]
Nothing has changed for me, I still have problems with hotplugging USB flash drives from time to time.

**Comment by Dunedan** [comment]
@peterychuang Any news on this? Can you provide any kind of logs for such problems?

**Comment by peterychuang** [comment]
The last time I checked, it seemed all the same to me. Unfortunately I couldn't see anything on logs when it failed.

I've switched back to macOS for now, since I'm too busy to be fiddling with the machine, so I wouldn't be able to test anything for the time being...

**Comment by Dunedan** [comment]
All right. As you're the only user experiencing this problem so far and won't be able to investigate further, I'm closing this issue for now. Let's reopen it, when that changes.
