### ISSUE TITLE
“suspend/resume work with some notable caveats. Need to write it up.”

### ISSUE THREAD

**Issue by puellanivis** [Dunedan/mbp-2016-linux#49]
https://github.com/Dunedan/mbp-2016-linux/issues/29#issuecomment-355379958

Have a tracking bug. ;)

**Comment by Dunedan** [comment]
We already have one (https://github.com/Dunedan/mbp-2016-linux/issues/37), so I'm closing this one.

Oh and one of the mentioned caveats is that it doesn't work for the Touch Bar models. :wink:
