### ISSUE TITLE
rosnodes break wifi

### ISSUE THREAD

**Issue by geoeo** [Dunedan/mbp-2016-linux#50]
Hi,

I just wanted to mention that running a rosnode will force the wifi to stop working after a couple of minutes. MBP 13,1 late 2017
This happens even when the nodes are running on the same machine.

[ROS](http://www.ros.org/).
Thank you for your efforts!

Best,
Marc

**Comment by Dunedan** [comment]
This repository provides information about the status of working hardware for recent MacBook Pro's and provides a place to discuss how to get the different components working.

As wifi for the MacBookPro 13,1 and MacBookPro 14,1 is properly working with multiple Linux distributions, I suggest you open [a bug report with the developers of ROS](http://wiki.ros.org/Tickets) or in the [Linux Kernel Bugtracker](https://bugzilla.kernel.org/).
