### ISSUE TITLE
MBP 14.3 Fixed Wi-Fi, but only 2.4GHz

### ISSUE THREAD

**Issue by ivanrigovsky** [Dunedan/mbp-2016-linux#63]
I just added 
`sudo iwconfig wlp3s0 txpower 10dBm `
and it's working ok now. 
Previous value 31dBm
**But only 2.4GHz**

**Comment by mzanetti** [comment]
Just to confirm that I've been using this now for an entire day without an issue. I did video calls and lots of other web related activities. Not a single connection drop. I seem to get 30Mb/s downstream which is not great, but oh well, it works at least.

Thanks so much for providing this information. I really got fed up with using a USB WiFi dongle.

**Comment by ivanrigovsky** [comment]
@mzanetti  I'm glad to hear it :) Also only 2.4GHz?

**Comment by jboyens** [comment]
If you use the patched firmware referenced elsewhere, you can get less
stable 5Ghz, but it's good enough to be usable long-term.

**Comment by mhkabir** [comment]
@jboyens how do we acquire this patched firmware?

**Comment by jboyens** [comment]
https://github.com/Dunedan/mbp-2016-linux/issues/47

**Comment by Dunedan** [comment]
As all MacBook Pro models with Touch Bar use the same wifi chip, let's keep the discussion in a single issue: #47 
Therefore closing this.
