### ISSUE TITLE
synaptics driver now working properly for me

### ISSUE THREAD

**Issue by mzanetti** [Dunedan/mbp-2016-linux#64]
When I first installed my MBP mid 2017 touchbar in autumn 2017, the synaptics driver would not work properly and I only could make the touchpad working reasonably well with libinput.

Today I upgraded the notebook to Ubuntu 18.04 and this messed up my xinput configuration. Palm detection, disable-tapping-while-typing, loads of stuff wasn't working any more. After trying to re-configure it for a while I decided to give synaptics another go and it seems to do the job perfectly fine by now. With libinput I could not configure the touchpad in KDE's system settings, this works fine with synaptics now. Also normal pointer speed settings seem to work with it, while with libinput I had to fiddle with the Transformation matrix to achieve a reasonable speed with in turn was breaking some edge panel stuff before.

Hope this information helps people who are struggling with the touchpad.

**Comment by Dunedan** [comment]
:+1: Awesome. Thanks for mentioning.

As it just works without any additional effort, I think it neither does make sense to include it into the README nor to keep this issue open. If you believe it should be added to the README feel free to open a pull request.
