### ISSUE TITLE
MBP 13,1 - Can't install grub to the main SSD. "Unknown filesystem"

### ISSUE THREAD

**Issue by 0x0f0f0f** [Dunedan/mbp-2016-linux#77]
SIP is disabled correctly. I can access the ESP perfectly but `grub-install`, `grub-probe` and `update-grub` all fail reporting "unknown filesystem" on /dev/nvme0n1 (the main SSD drive).

Tried with the latest grub from ubuntu 18.10 repositories, compiled from source and from void linux repositories.

Booting through other bootloaders (systemd-boot, ELILO, refind) leaves my mbp with a dead black screen or a kernel booted in blind mode.

**Comment by 0x0f0f0f** [comment]
Thank you! I'll try

**Comment by 0x0f0f0f** [comment]
Worked. Can you specify in instructions to install grub in a secondary EFI partition?

**Comment by roadrunner2** [comment]
Sorry, I'm confused. What exactly worked, and what exactly do you mean by a secondary EFI partition here? (you're giving me very little info about what your setup is and what you're doing)

**Comment by 0x0f0f0f** [comment]
```Device            Start      End  Sectors   Size Type
/dev/nvme0n1p1        6    76805    76800   300M EFI System
/dev/nvme0n1p2    76806 39795464 39718659 151,5G unknown
/dev/nvme0n1p3 39795465 51289093 11493629  43,9G Microsoft basic data
/dev/nvme0n1p4 51289094 51321861    32768   128M Apple boot
/dev/nvme0n1p5 51321862 51346276    24415  95,4M Microsoft basic data
/dev/nvme0n1p6 51346277 60201828  8855552  33,8G Linux filesystem
/dev/nvme0n1p7 60201984 61246570  1044587     4G Linux swap
/dev/nvme0n1p8 61246571 61279338    32768   128M Apple boot
```

grub is installed in `/dev/nvme0n1p5` and booted through refind (installed in `/dev/nvme0n1p1`).

I have a problem with multiple distros (i'm now booting ubuntu cosmic cuttlefish budgie), when installing grub the configuration isn't picked up correctly and the menu isn't displayed during boot, it shows a blue screen for a brief frame and then crashes directly to the grub command line without any error message. I have to load and boot the kernel manually. It also says it's booting in blind mode bc no suitable video mode was found. What can be causing this and how should i config grub?

**Comment by 0x0f0f0f** [comment]
4.18.0-7-generic kernel

**Comment by 0x0f0f0f** [comment]
grub-install (GRUB) 2.02+dfsg1-5ubuntu2

**Comment by roadrunner2** [comment]
My resulting grub.cfg contains the following for video:
```
function load_video {
  if [ x$feature_all_video_module = xy ]; then
    insmod all_video
  else
    insmod efi_gop
    insmod efi_uga
    insmod ieee1275_fb
    insmod vbe
    insmod vga
    insmod video_bochs
    insmod video_cirrus
  fi
}

terminal_output console
...
menuentry ... {
        load_video
        ....
}
```

**Comment by 0x0f0f0f** [comment]
Fixed by generating the correct grub config
