### ISSUE TITLE
status of Arch on 14,1

### ISSUE THREAD

**Issue by mfauvain** [Dunedan/mbp-2016-linux#80]
Wanted to post here experience I have with 14,1 and Arch, so far
- boots fine with 4.16 kernels, black screen with 4.18, haven't tried 4.17
- wifi works with brcmfmac however slow (speed of 25Mb/s). tried broadcom-wl-dkms no luck.
- bluetooth not showing. any help here much appreciated.
- facetimehd not working in cheese for ex. (driver bcwc_pcie installed without errors though)
- thunderbolt and thunderbolt display works out of the box, even with accesories connected. Even display hotplug I believe (which is a progress from previous macbook with linux). 
- and of course suspend/resume + sound not working

general experience (arch+gnome) is good. need to fix those few issues (esp bluetooth) and will be up and running.

**Comment by Dunedan** [comment]
None of these points are particularly new and they are all covered in either the README or existing issues. As this repository is about general Linux support and doesn't cover individual Linux distributions I'm going to close this now. If you encounter bugs or problems, which aren't covered by existing issues yet, please open new issues, but one per topic.
