### ISSUE TITLE
Can we get a Linux MBP community?

### ISSUE THREAD

**Issue by tomaytotomato** [Dunedan/mbp-2016-linux#83]
@Dunedan 

Could we have a gitter / slack or other suitable collaboration site setup?

I am a fairly novice/intermediate Linux user and its been great to find this repository however:

* It is not easy to find or understand information on here
* Collaboration is good but it could be much better with realtime interactions were people could hack Linux on MBP
* There's groups of people on here by Mac hardware type and Linux distros, so it would be nice to find other people by those criteria.
* Myself and I am sure others would like to make this a big community, that grows and helps each other out.

Thanks for everything so far. 

I am really enjoying my Macbook Pro 13,1 despite some quirks. It has made me become a productive developer again who was used to Linux on Thinkpads.
I will be sharing my performance readings but the MBP 13,1 for me is definitely better battery, memory and processor usage, compared with MacOS Mojave

**Comment by Dunedan** [comment]
The focus of this repository is not to provide step-by-step instructions for end-users of how to get the various Linux distributions running properly on MacBook Pros. Instead its focus is to bring together experienced Linux users, who want to participate in improving the support for such MacBook Pro's, eventually getting such support upstreamed so all Linux users, no matter what Linux distribution they use, can benefit from it.

That said I see benefit from having a more realtime-focused communication channel, so I added a gitter-community: https://gitter.im/mbp-2016-linux/Lobby
I personally will be online there only occasionally, but maybe others will be there more often.
