### ISSUE TITLE
Could you share MacBookPro14,3 ACPI & IOREG & SPX dumps

### ISSUE THREAD

**Issue by RockJesus** [Dunedan/mbp-2016-linux#84]
Hi Could you share MacBookPro14,3 ACPI & IOREG & SPX dumps ,Thx

**Comment by ClashTheBunny** [comment]
What's missing from my dump?

**Comment by ClashTheBunny** [comment]
I installed `acpidump` and re-ran.  Is that better?

**Comment by RockJesus** [comment]
Thx a lot

[IORegistryExplorer.app.zip](https://github.com/Dunedan/mbp-2016-linux/files/2546676/IORegistryExplorer.app.zip)
Using this app on macos could get a dump of Ioreg file ,I’m truly grateful for your help!

**Comment by ClashTheBunny** [comment]
I'm not big into running random binaries off the internet.  Maybe somebody else here has the guts to run those?

**Comment by RockJesus** [comment]
ok,anyway,Thx for help

**Comment by Dunedan** [comment]
@RockJesus: What do you need that data for? Is it Hackintosh related?

**Comment by RockJesus** [comment]
> @RockJesus: What do you need that data for? Is it Hackintosh related?

Yes,any help will be appreciated!
