### ISSUE TITLE
How to enable 3 finger drag in xfce

### ISSUE THREAD

**Issue by duchengyao** [Dunedan/mbp-2016-linux#93]
Thanks for your awesome project!

I'm using Ubuntu 16.04 Xfce edition, and I want to fit the touch-pad to my mac.
I enable some feature by adding the following lines to `/usr/share/X11/xorg.conf.d/70-synaptics.conf`

```
        Option "VertScrollDelta" "-303"
        Option "HorizEdgeScroll" "1"
        Option "HorizTwoFingerScroll" "1"
        Option "HorizEdgeScroll" "0"
        Option "LockedDrags" "1"
        Option "LockedDragTimeout" "1000"
```

But how to enable 3 finger drag like macbook? 
I have tried to install `xserver-xorg-input-mtrack-hwe-16.04` but nothing happens.

Thanks so much!

**Comment by Dunedan** [comment]
As nobody did seem to have an answer to this question and as this question isn't really about hardware support (it's probably just something not implemented in the Linux drivers) I'm closing this issue now.
